/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_dzikoysk_linuxenv_LinuxJVMEnvironment */

#ifndef _Included_net_dzikoysk_linuxenv_LinuxJVMEnvironment
#define _Included_net_dzikoysk_linuxenv_LinuxJVMEnvironment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_dzikoysk_linuxenv_LinuxJVMEnvironment
 * Method:    unsetJVMEnvironmentVariable
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_dzikoysk_linuxenv_LinuxJVMEnvironment_unsetJVMEnvironmentVariable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_dzikoysk_linuxenv_LinuxJVMEnvironment
 * Method:    setJVMEnvironmentVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_dzikoysk_linuxenv_LinuxJVMEnvironment_setJVMEnvironmentVariable
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     net_dzikoysk_linuxenv_LinuxJVMEnvironment
 * Method:    getJVMEnvironmentVariable
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_dzikoysk_linuxenv_LinuxJVMEnvironment_getJVMEnvironmentVariable
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
